### PR TITLE
Add Madrid March&April 2016 meetings

### PR DESCRIPTION
**Pull request by adrianblanco**
Good luck with the election! 
Thanks!

### CODE REVIEW

**Comment by adrianblanco** [comment]
Good luck with the election!

**Comment by adrianblanco** [comment]
Thanks! Not sure why the website is not showing the changes  ¯_(ツ)_/¯

**Comment by ejb** [comment]
Check issue #3 – we need to update to Jekyll 3.

**Comment by adrianblanco** [comment]
Ah yes, I saw it the other day but I did not remember. It is not supported. I'll try to take a look this weekend!

**Pull request merged**
